services:
  - type: web
    name: electoral-sys-api
    env: node
    buildCommand: cd src-api && npm install && npm run build
    startCommand: cd src-api && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        sync: false